services:
  gateway:
    build: ./ms-gateway
    ports:
      - "8080:8080"
    environment:
      - URL_ASISTENCIA=http://ms-asistencia:8082
      - URL_SUSCRIPCIONES=http://ms-suscripciones:8083
      - URL_PAGOS=http://ms-pagos:8084
    depends_on:
      - ms-asistencia
      - ms-suscripciones
      - ms-pagos

  ms-asistencia:
    build: ./ms-asistencia
    ports:
      - "8082:8082"

  ms-suscripciones:
    build: ./ms-suscripciones
    ports:
      - "8083:8083"

  ms-pagos:
    build: ./ms-pagos
    ports:
      - "8084:8084"
    environment:
      - URL_SUSCRIPCIONES=http://ms-suscripciones:8083
